### ISSUE TITLE
compiled extensions are not cached

### ISSUE THREAD

**Issue by cainlevy** [c-hive/gha-npm-cache#10]
This GH Action will cache the OS-specific NPM directory, as per [official recommendation](https://github.com/actions/cache/blob/9ab95382c899bf0953a0c6c1374373fc40456ffe/examples.md#node---npm). However this will not include compiled targets that modules ensure on `postinstall`, which (in my case) are found in `node_modules`.

I'm guessing this kind of support is out of scope for gha-npm-cache, but I want to create a paper trail for others.

**Comment by thisismydesign** [comment]
Thanks, yes, that's how it works. It would be reasonable to have an `unsafe-cache-node-modules` option. When turned on it would cache `node_modules` instead. Would you provide a PR for this?

**Comment by cainlevy** [comment]
I found a more targeted workaround for my case. My dependency has a ENV var that disables compilation, so I set that during `npm install` and then ran the postinstall later with manual caching. It looks something like this:

```yml
- uses: c-hive/gha-npm-cache@v1
- name: Install node modules
  run: npm install
  env:
    # 1. find (or contribute) an ENV flag to disable postinstall behavior
    MY_MODULE_ENV_FLAG: "do-not-compile"

# 2. cache the build directory, keyed to the package version
- uses: actions/cache@v1
  with:
    path: "./node_modules/my_module/path/to/compile/target"
    key: my_module-${{ runner.os }}-${{ hashFiles('./node_modules/my_module/package.json') }}
# 3. run the skipped postinstall after restoring the build cache
- name: Compile
  run: |
    cd ./node_modules/my_module
    npm run postinstall
```

I haven't observed this more than once, so I don't know if the pattern generalizes. Hopefully this helps the next person!
